project_name: Minimal Example
repository_url: https://github.com/kolibril13/plywood-gallery-minimal-example
user_content_version: 1.22.3
description: |
  Minimal example for plywood gallery cheat sheets
favicon: icon.png 
preview_image: https://kolibril13.github.io/plywood-gallery-minimal-example/preview_image.png
gallery_parameters_path: gallery_assets/gallery_parameters.json
