project_name: Plywood Gallery - Minimal Example
user_content_version: 1.22.3
description: |
  Normal cells are independent of each other, and can be run togehter with the "Header" cell. <br>
  A "Dependent" cell depends on the "Normal" cell left to it. <br>
  A "Dependent" cell depends on another "Dependent" cell left to it.
favicon: plywood_icon.png # favicon that will be shown in the task bar, prefered resolution: 32x32 pixel. Formats: `.png` or `.ico`.
gallery_parameters_path: gallery_assets/gallery_parameters.json

# Parameter for webpage only 
custom_footer: |
  <div style="position: fixed; bottom: 10px; right:10px"> <a href="https://github.com/kolibril13/plywood-gallery">
  Link to the original plywood core repo.</a></div>
repository_url: https://github.com/kolibril13/plywood-gallery-minimal-example

# Parameter for Extension only 
preview_image: thumbnail.png  # Gallery thumbnail that is shown in the gallery explorer, prefered resolution:  at least 300x300 pixel. Format: `.png` 

